/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LoginController;
import Models.LoginModel;
import Models.Data.Staff;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author nguye
 */
public class Login extends javax.swing.JFrame {
    public static String FullNameStaff;
    public static String Role;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setTitle("Login");
        setSize(645, 536);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Đặt màu nền cho SignIn JFrame
        Color color = new Color(254, 231, 199);
        getContentPane().setBackground(color); // Sửa màu nền thành màu trắng
//        ImageIcon imageIcon = new ImageIcon("img.jpg");
//        JLabel label = new JLabel(imageIcon);
//        getContentPane().add(label, BorderLayout.CENTER);
        // Set frame ở giữa màn hình
        this.setLocationRelativeTo(null);
        // controller
//        controller = new StaffControllerImp();
        hiddenPass_Icon.setVisible(false);
        Color color_btn = new Color(173, 121, 91);
        btn__Login.setBackground(color_btn);
        btn__Login.setForeground(Color.WHITE);
        btn__SignIn.setBackground(color_btn);
        btn__SignIn.setForeground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_UserName = new javax.swing.JTextField();
        btn__Login = new javax.swing.JButton();
        btn__SignIn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        showPass_Icon = new javax.swing.JLabel();
        hiddenPass_Icon = new javax.swing.JLabel();
        lbl__Password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(173, 121, 91));
        jLabel1.setText("Đăng nhập");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 180, 190, 43);
        getContentPane().add(lbl_UserName);
        lbl_UserName.setBounds(200, 230, 192, 30);

        btn__Login.setLabel("Đăng nhập");
        btn__Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn__LoginActionPerformed(evt);
            }
        });
        btn__Login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn__LoginKeyPressed(evt);
            }
        });
        getContentPane().add(btn__Login);
        btn__Login.setBounds(300, 310, 88, 30);

        btn__SignIn.setText("Đăng ký");
        btn__SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn__SignInActionPerformed(evt);
            }
        });
        getContentPane().add(btn__SignIn);
        btn__SignIn.setBounds(240, 400, 90, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Screenshot 2023-10-07 154826.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 30, 230, 140);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cyber-security-1915628_1280.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 270, 30, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon_User.png"))); // NOI18N
        jLabel6.setText("jLabel4");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(170, 230, 30, 30);

        jLabel3.setText("Bạn chưa có tài khoản?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 370, 130, 16);

        showPass_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/4830332-200.png"))); // NOI18N
        showPass_Icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showPass_IconMouseClicked(evt);
            }
        });
        getContentPane().add(showPass_Icon);
        showPass_Icon.setBounds(400, 270, 30, 30);

        hiddenPass_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tải 1.png"))); // NOI18N
        hiddenPass_Icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hiddenPass_IconMouseClicked(evt);
            }
        });
        getContentPane().add(hiddenPass_Icon);
        hiddenPass_Icon.setBounds(400, 270, 30, 30);
        getContentPane().add(lbl__Password);
        lbl__Password.setBounds(200, 270, 190, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn__LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn__LoginActionPerformed
        // TODO add your handling code here:
        String UserName = lbl_UserName.getText();
        String PassWord = lbl__Password.getText();
        LoginModel loginModel = new LoginModel();
        LoginController loginController = new LoginController(loginModel);
        Staff staff = new Staff();
        staff.setEmail(UserName);
        staff.setPasswordHas(PassWord);
        if(loginController.Login(staff)) {
            JOptionPane.showMessageDialog(this, "Đăng nhập thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            // Get FullName
            FullNameStaff =  loginController.GetFullNameStaff(UserName, PassWord);
            Role = loginController.getRoleUser(UserName, PassWord);
            staff.setFullName(UserName);
            // Get Role
            
            HomeStaff HomeStaffFrame = new HomeStaff();
            HomeStaffFrame.setVisible(true);
            this.setVisible(false);
        }
        else {
            JOptionPane.showMessageDialog(this, "Đăng nhập thất bại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn__LoginActionPerformed

    private void btn__SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn__SignInActionPerformed
        // TODO add your handling code here:
        SignUp SignUpFrame = new SignUp();
        SignUpFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn__SignInActionPerformed

    private void btn__LoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn__LoginKeyPressed
        // TODO add your handling code here:
        String UserName = lbl_UserName.getText();
        String PassWord = lbl__Password.getText();
        LoginModel loginModel = new LoginModel();
        LoginController loginController = new LoginController(loginModel);
        Staff staff = new Staff();
        staff.setEmail(UserName);
        staff.setPasswordHas(PassWord);
        if(loginController.Login(staff)) {
            JOptionPane.showMessageDialog(this, "Đăng nhập thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            // Get FullName
            FullNameStaff =  loginController.GetFullNameStaff(UserName, PassWord);
            Role = loginController.getRoleUser(UserName, PassWord);
            staff.setFullName(UserName);
            // Get Role
            
            HomeStaff HomeStaffFrame = new HomeStaff();
            HomeStaffFrame.setVisible(true);
            this.setVisible(false);
        }
        else {
            JOptionPane.showMessageDialog(this, "Đăng nhập thất bại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn__LoginKeyPressed

    private void showPass_IconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPass_IconMouseClicked
        // TODO add your handling code here:
        hiddenPass_Icon.setVisible(true);
        showPass_Icon.setVisible(false);
        char echoChar = lbl__Password.getEchoChar();
        lbl__Password.setEchoChar((echoChar == 0) ? '\u2022' : '\0');
    }//GEN-LAST:event_showPass_IconMouseClicked

    private void hiddenPass_IconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hiddenPass_IconMouseClicked
        // TODO add your handling code here:
        hiddenPass_Icon.setVisible(false);
        showPass_Icon.setVisible(true);
        char echoChar = lbl__Password.getEchoChar();
        lbl__Password.setEchoChar('*');
    }//GEN-LAST:event_hiddenPass_IconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn__Login;
    private javax.swing.JButton btn__SignIn;
    private javax.swing.JLabel hiddenPass_Icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField lbl_UserName;
    private javax.swing.JPasswordField lbl__Password;
    private javax.swing.JLabel showPass_Icon;
    // End of variables declaration//GEN-END:variables
}
