/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.MemberController;
import Models.Data.Member;
import Models.Data.Staff;
import Models.LoginModel;
import Models.MemberModel;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;

/**
 *
 * @author nguye
 */
public class HomeStaff extends javax.swing.JFrame  {
    /**
     * Creates new form HomeStaff
     */
    public HomeStaff() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        Color color1 = new Color(254, 231, 199);
        getContentPane().setBackground(color1);
        Color color = new Color(173, 121, 91);
        btn_Account.setBackground(color);
        btn_Account.setForeground(Color.WHITE);
        btn_ManagerTable.setBackground(color);
        btn_ManagerTable.setForeground(Color.WHITE);
        btn_InfoCus.setBackground(color);
        btn_InfoCus.setForeground(Color.WHITE);
        btn_MenuManager.setBackground(color);
        btn_MenuManager.setForeground(Color.WHITE);
        btn_HRM.setBackground(color);
        btn_HRM.setForeground(Color.WHITE);
        btn_Report_Sales.setBackground(color);
        btn_Report_Sales.setForeground(Color.WHITE);
        btn_Invoice_statistics.setBackground(color);
        btn_Invoice_statistics.setForeground(Color.WHITE);
        btn_Logout.setBackground(color);
        btn_Logout.setForeground(Color.WHITE);
        btn_search.setBackground(color);
        btn_search.setForeground(Color.WHITE);
        
        MemberModel memberModel = new MemberModel();
        MemberController memberController = new MemberController(memberModel);
        Member member = new Member();
        Staff staff = new Staff();
        List<Member> listMember = memberController.getAllmember();
        DefaultTableModel model = (DefaultTableModel)jTbl_Customer.getModel();
        for(Member o : listMember){
            model.addRow(new Object[] {
                o.getiD(),
                "0"+o.getPhoneNumber(),
                o.getNameCustomer(),
                o.getStartDate(),
                o.getRevenue(),
                o.getScore()
            
            });
        }
        jLabel4.setText(Login.FullNameStaff);
//        LocalDate currentDate = LocalDate.now();
//        String DateString = currentDate.toString();
        LocalDate currentDate = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String formattedDate = currentDate.format(formatter);

        // Tạo một JLabel và thiết lập nội dung
        jLabel2.setText("Ngày hiện tại: " + formattedDate);
        if("Quản lý".equals(Login.Role)) {
            btn_MenuManager.setVisible(true);
            btn_HRM.setVisible(true);
            btn_Report_Sales.setVisible(true);
            btn_Invoice_statistics.setVisible(true);
        }
        else {
            btn_MenuManager.setVisible(false);
            btn_HRM.setVisible(false);
            btn_Report_Sales.setVisible(false);
            btn_Invoice_statistics.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_MenuManager = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_Account = new javax.swing.JButton();
        btn_Logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbl_Customer = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        btn_ManagerTable = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_HRM = new javax.swing.JButton();
        btn_Report_Sales = new javax.swing.JButton();
        btn_Invoice_statistics = new javax.swing.JButton();
        btn_InfoCus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_MenuManager.setText("Quản lý thực đơn");
        btn_MenuManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenuManagerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_MenuManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 144, 28));

        jLabel1.setText("Chức năng");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 152, -1));

        btn_Account.setText("Tài khoản");
        btn_Account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AccountActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Account, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 149, -1));

        btn_Logout.setText("Đăng xuất");
        btn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 149, -1));

        jLabel2.setText("Ngày hiện tại");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 140, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Thông tin khách hàng thành viên");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 417, -1));

        jTbl_Customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Số điện  thoại", "Tên khách hàng", "Ngày tham gia", "Doanh số", "Điểm tích lũy"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTbl_Customer);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 179, 640, 470));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 183, -1));

        btn_search.setText("Tìm kiếm");
        getContentPane().add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        btn_ManagerTable.setText("Quản lý bàn");
        btn_ManagerTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ManagerTableActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ManagerTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 145, 28));

        jLabel4.setText("Staff Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 117, -1));

        jLabel5.setText("Xin chào: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 52, -1));

        btn_HRM.setText("Quản lý nhân sự");
        btn_HRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HRMActionPerformed(evt);
            }
        });
        getContentPane().add(btn_HRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 144, 28));

        btn_Report_Sales.setText("Báo cáo doanh thu");
        btn_Report_Sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Report_SalesActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Report_Sales, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 144, 28));

        btn_Invoice_statistics.setText("Thống kê hóa đơn");
        btn_Invoice_statistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Invoice_statisticsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Invoice_statistics, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 145, 28));

        btn_InfoCus.setText("Thông tin khách hàng");
        getContentPane().add(btn_InfoCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 146, 28));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo_min.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 80, 90));

        jLabel7.setText("Thông tin cá nhân");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 152, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogoutActionPerformed
        Login loginFrame = new Login();
        loginFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_LogoutActionPerformed

    private void btn_ManagerTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ManagerTableActionPerformed
        TableManager TableManagerFrame = new TableManager();
        TableManagerFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ManagerTableActionPerformed

    private void btn_AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AccountActionPerformed

    private void btn_MenuManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenuManagerActionPerformed
        // TODO add your handling code here:
        MenuManager MenuManagerFrame = new MenuManager();
        MenuManagerFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_MenuManagerActionPerformed

    private void btn_HRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HRMActionPerformed
        // TODO add your handling code here:
        HrManager hrManagerFrame = new HrManager();
        hrManagerFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_HRMActionPerformed

    private void btn_Report_SalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Report_SalesActionPerformed
        reportRevenue report = new reportRevenue();
        report.setVisible(true);

    }//GEN-LAST:event_btn_Report_SalesActionPerformed

    private void btn_Invoice_statisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Invoice_statisticsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Invoice_statisticsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Account;
    private javax.swing.JButton btn_HRM;
    private javax.swing.JButton btn_InfoCus;
    private javax.swing.JButton btn_Invoice_statistics;
    private javax.swing.JButton btn_Logout;
    private javax.swing.JButton btn_ManagerTable;
    private javax.swing.JButton btn_MenuManager;
    private javax.swing.JButton btn_Report_Sales;
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbl_Customer;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
