/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LoginController;
import Controller.ValidateController;
import Models.LoginModel;
import Models.Data.Staff;
import Models.ValidateModel;
import java.awt.Color;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
/**
 *
 * @author nguye
 */
public class SignUp extends javax.swing.JFrame {
     private String Code = null;
     Staff staff = new Staff();
    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        txt_Code.setFocusable(false);
        jbl_Code.setFocusable(false);
        btn_ConfirmCode.setEnabled(false);
        ChangeColor();
    }
    
    
    private void ChangeColor() {
        Color colorBackGround = new Color(254, 231, 199);
        Color color = new Color(173,121,91);
        getContentPane().setBackground(colorBackGround);
        jLabel11.setForeground(color);
        jLabel12.setForeground(color);
        jLabel13.setForeground(color);
        jLabel14.setForeground(color);
        btn__SignIn.setBackground(color);
        btn__SignUp.setBackground(color);
        btn__SignIn.setForeground(Color.WHITE);
        btn__SignUp.setForeground(Color.WHITE);
        btn_ConfirmCode.setBackground(color);
        btn_ConfirmCode.setForeground(Color.WHITE);
        lbl__FirstName.setBorder(new LineBorder(color));
        lbl__LastName.setBorder(new LineBorder(color));
        jDC_DOB.setBorder(new LineBorder(color));
        cbb__Gender.setBorder(new LineBorder(color));
        lbl__PhoneNumber.setBorder(new LineBorder(color));
        lbl__UserName.setBorder(new LineBorder(color));
        lbl__Password.setBorder(new LineBorder(color));
        lbl__ConfirmPass.setBorder(new LineBorder(color));
        txt_Code.setBorder(new LineBorder(color));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl__PhoneNumber = new javax.swing.JTextField();
        lbl__Password = new javax.swing.JTextField();
        lbl__FirstName = new javax.swing.JTextField();
        btn__SignIn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn__SignUp = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbb__Gender = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl__ConfirmPass = new javax.swing.JTextField();
        lbl__LastName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lbl__UserName = new javax.swing.JTextField();
        jDC_DOB = new com.toedter.calendar.JDateChooser();
        jbl_Code = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_Code = new javax.swing.JTextField();
        btn_ConfirmCode = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng ký");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel7.setText("Nhập lại mật khẩu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 70, 0, 0);
        getContentPane().add(jLabel7, gridBagConstraints);

        jLabel8.setText("Mật khẩu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 70, 0, 0);
        getContentPane().add(jLabel8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 28;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.ipadx = 310;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 71, 0, 66);
        getContentPane().add(lbl__PhoneNumber, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 20;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.ipadx = 309;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 71, 0, 0);
        getContentPane().add(lbl__Password, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 112;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 71, 0, 0);
        getContentPane().add(lbl__FirstName, gridBagConstraints);

        btn__SignIn.setText("Đăng nhập");
        btn__SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn__SignInActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 47;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 110, 42, 0);
        getContentPane().add(btn__SignIn, gridBagConstraints);

        jLabel2.setText("Họ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 71, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        btn__SignUp.setText("Đăng ký");
        btn__SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn__SignUpActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 47;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 32;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 90, 42, 0);
        getContentPane().add(btn__SignUp, gridBagConstraints);

        jLabel3.setText("Tên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 34, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setText("Ngày sinh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 71, 0, 0);
        getContentPane().add(jLabel4, gridBagConstraints);

        jLabel5.setText("Số điện thoại");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 71, 0, 0);
        getContentPane().add(jLabel5, gridBagConstraints);

        cbb__Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.ipadx = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 34, 0, 66);
        getContentPane().add(cbb__Gender, gridBagConstraints);

        jLabel6.setText("Giới tính");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 34, 0, 0);
        getContentPane().add(jLabel6, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Tạo tài khoản");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 32;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 122, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 31;
        gridBagConstraints.gridwidth = 20;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.ipadx = 309;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 71, 0, 0);
        getContentPane().add(lbl__ConfirmPass, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 34, 0, 66);
        getContentPane().add(lbl__LastName, gridBagConstraints);

        jLabel9.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 70, 0, 0);
        getContentPane().add(jLabel9, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 20;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 309;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 71, 0, 0);
        getContentPane().add(lbl__UserName, gridBagConstraints);

        jDC_DOB.setDateFormatString("dd MMM, yyyy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 94;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 71, 0, 0);
        getContentPane().add(jDC_DOB, gridBagConstraints);

        jbl_Code.setText("Nhập mã ccode");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 45;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 71, 0, 0);
        getContentPane().add(jbl_Code, gridBagConstraints);

        jLabel10.setBackground(new java.awt.Color(173, 121, 91));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 8;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 90, 0, 0);
        getContentPane().add(jLabel10, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 46;
        gridBagConstraints.gridwidth = 20;
        gridBagConstraints.ipadx = 309;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 71, 0, 0);
        getContentPane().add(txt_Code, gridBagConstraints);

        btn_ConfirmCode.setText("Xác minh");
        btn_ConfirmCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConfirmCodeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 47;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 42, 0);
        getContentPane().add(btn_ConfirmCode, gridBagConstraints);

        jLabel11.setBackground(new java.awt.Color(173, 121, 91));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel11.setText("Rambo Coffee");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 70, 0, 0);
        getContentPane().add(jLabel11, gridBagConstraints);

        jLabel13.setBackground(new java.awt.Color(173, 121, 91));
        jLabel13.setText("Nếu bạn muốn sử dụng dịch vụ tại đây ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 80, 0, 0);
        getContentPane().add(jLabel13, gridBagConstraints);

        jLabel12.setBackground(new java.awt.Color(173, 121, 91));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel12.setText("Welcome to");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 90, 0, 0);
        getContentPane().add(jLabel12, gridBagConstraints);

        jLabel14.setBackground(new java.awt.Color(173, 121, 91));
        jLabel14.setText("vui lòng đăng nhập với tài khoản cá nhân của bạn ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 37;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 8;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 0);
        getContentPane().add(jLabel14, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn__SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn__SignInActionPerformed
        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn__SignInActionPerformed
    
    private void btn__SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn__SignUpActionPerformed
        // TODO add your handling code here:
        String firstName = lbl__FirstName.getText();
        String lastName = lbl__LastName.getText();
        
        Date selectDate = jDC_DOB.getDate();
        java.sql.Date sqlDate = new java.sql.Date(selectDate.getTime());
        
        Object SelectGender = cbb__Gender.getSelectedItem();
        String gender = SelectGender.toString();
        int phoneNumber = Integer.parseInt(lbl__PhoneNumber.getText());
        String email = lbl__UserName.getText();
        String password = lbl__Password.getText();
        String ConfirmPass = lbl__ConfirmPass.getText();
        
        LoginModel loginModel = new LoginModel();
        LoginController loginController = new LoginController(loginModel);
        Date date = new Date();
        staff.firstName = firstName;
        staff.lastName = lastName;
        if(sqlDate == null) {
            staff.dob = date;
        }
        else {
            staff.dob = sqlDate;
        }
        staff.gender = gender;
        staff.phoneNumber = phoneNumber;
        staff.Email = email;
        staff.passwordHas = password;
        
        if(password == null ? ConfirmPass != null : !password.equals(ConfirmPass)) {
            JOptionPane.showMessageDialog(this, "Mật khẩu không trùng khớp", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else {
            txt_Code.setFocusable(false);
            jbl_Code.setFocusable(false);
            btn_ConfirmCode.setEnabled(false);
            ValidateModel _valiDate = new ValidateModel();
            ValidateController validateController = new ValidateController(_valiDate);
            if(validateController.validateEmail(staff.Email) && validateController.validatePass(staff.passwordHas) && validateController.validatePhone(staff.phoneNumber)) {
                SendMail(lbl__UserName.getText());
            }
            else {
                JOptionPane.showMessageDialog(this, "Email, Số điện thoại hoặc mật khẩu không hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btn__SignUpActionPerformed

    private void btn_ConfirmCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConfirmCodeActionPerformed
        // TODO add your handling code here:
        LoginModel loginModel = new LoginModel();
        LoginController loginController = new LoginController(loginModel);
        
        
        if(txt_Code.getText() == null ? Code == null : txt_Code.getText().equals(Code)) {
            if(loginController.SignUp(staff)) {
            JOptionPane.showMessageDialog(this, "Đăng ký thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            Login LoginFrame = new Login();
            LoginFrame.setVisible(true);
            this.setVisible(false);
            }
            else {
                JOptionPane.showMessageDialog(this, "Đăng ký không thành công", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Mã code không hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_ConfirmCodeActionPerformed

    private void SendMail(String Email) {
        Random random = new Random();
        int randomNumber = random.nextInt(999999) + 1;
        Code = String.valueOf(randomNumber);
        LoginModel loginModel = new LoginModel();
        LoginController loginController = new LoginController(loginModel);
        loginController.SendMail(Email, String.valueOf(randomNumber));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ConfirmCode;
    private javax.swing.JButton btn__SignIn;
    private javax.swing.JButton btn__SignUp;
    private javax.swing.JComboBox<String> cbb__Gender;
    private com.toedter.calendar.JDateChooser jDC_DOB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jbl_Code;
    private javax.swing.JTextField lbl__ConfirmPass;
    private javax.swing.JTextField lbl__FirstName;
    private javax.swing.JTextField lbl__LastName;
    private javax.swing.JTextField lbl__Password;
    private javax.swing.JTextField lbl__PhoneNumber;
    private javax.swing.JTextField lbl__UserName;
    private javax.swing.JTextField txt_Code;
    // End of variables declaration//GEN-END:variables
}
